using System;
using System.Collections.Generic;
using System.Text;

namespace P3bble.Constants
{
    public enum Icons
    {
        bell = 1,
        cell_phone_reject = 2,
        index_finger_up = 3,
        flag = 4,
        call = 5,
        twitter = 6,
        paper_plane = 7,
        quote = 8,
        gmail = 9,
        lightning_bolt = 10,
        facebook = 11,
        cassette = 12,
        alarm_clock = 13,
        rain_cloud_sun = 14,
        sun = 16,
        medal = 17,
        mail = 19,
        football = 20,
        calender = 21,
        ball = 22,
        tie = 23,
        car = 24,
        clouds = 25,
        cricket = 26,
        chef = 27,
        warning = 28,
        graph = 29,
        fallin_rock = 30,
        bell2 = 31,
        light_rain = 32,
        snow = 33,
        sign_to_right = 34,
        awesome = 35,
        letter_text = 36,
        cloud_and_sun = 37,
        radio = 39,
        clock_and_checkbox = 40,
        ball2 = 41,
        graph2 = 42,
        skull = 43,
        bottle_in_water = 45,
        paper_plane_2 = 47,
        cellphone = 49,
        hand_with_pink_up = 50,
        rain = 52,
        heavy_snow = 53,
        plane = 54,
        star = 55,
        sunsetting = 56,
        text_balloon = 58,
        camera = 59,
        open_envelope = 61,
        car_in_water = 62,
        question_mark = 63,
        outlook_mail = 64,
        snow_and_rain = 65,
        heart = 66,
        text_balloon2 = 67,
        skype = 68,
        ghost = 69,
        phone_ringing = 70,
        conversation = 71,
        yahoo_mail = 72,
        television = 73,
        ball3 = 74,
        cell_phone_without_reception = 75,
        text_balloon3 = 76,
        text_balloon_without_color = 77,
        cell_phone_ringing = 78,
        text_balloon_with_T = 79,
        Kdot = 80,
        lighthouse = 81,
        flag2 = 82,
        settings = 83,
        sunrise = 84,
        sunset = 85,
        video_recorder_off = 86,
        video_recorder_on = 87,
        video_recorder_arrow_up = 88,
        video_recorder_arrow_down_and_up = 89,
        video_recorder_sound = 90,
        spinning_triangle = 93
    }
}
